const CODE='STEP10',A=window.APP_DATA,P=A.id+':';let track=localStorage[P+'track']||Object.keys(A.tracks)[0],idx=0,gender='male',voices=[],xp=+(localStorage[P+'xp']||0),done=+(localStorage[P+'done']||0),best=localStorage[P+'best']||'—';const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="../enhancements.css">');
function enter(){$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');updateStreak();render();prepareVoices()}if(sessionStorage[P+'access']==='yes')enter();
function updateStreak(){let today=new Date().toISOString().slice(0,10),last=localStorage[P+'last'],streak=+(localStorage[P+'streak']||0);if(last!==today){let yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);streak=last===yesterday?streak+1:1;localStorage[P+'last']=today;localStorage[P+'streak']=streak}let box=$('.streak');if(box)box.textContent=`🔥 ${streak}일 연속 학습`}
$('#gateForm').onsubmit=e=>{e.preventDefault();if($('#accessCode').value.trim().toUpperCase()===CODE){sessionStorage[P+'access']='yes';enter()}else $('#gateError').textContent='초대 코드를 다시 확인해 주세요.'};$('#appName').textContent=A.name;$('#gateName').textContent=A.name;$('#gateSubtitle').textContent=A.subtitle;
function render(){let d=A.tracks[track];$('#tracks').innerHTML=Object.entries(A.tracks).map(([k,v])=>`<button class="track ${k===track?'active':''}" data-k="${k}">${v.name}</button>`).join('');$$('.track').forEach(b=>b.onclick=()=>{track=b.dataset.k;localStorage[P+'track']=track;idx=0;render()});$('#tag').textContent=d.tag;$('#title').textContent=d.name;$('#desc').textContent=d.desc;$('#xp').textContent=xp;$('#lessons').innerHTML=d.lessons.map((l,i)=>`<article class="lesson" role="button" tabindex="0" data-i="${i}"><div>${l[0]}</div><h4>${l[1]}</h4><p>${l[2]}</p><footer><span>${l[3]}</span><span>학습 시작 →</span></footer></article>`).join('');$$('.lesson').forEach(c=>{c.onclick=()=>openLesson(+c.dataset.i);c.onkeydown=e=>{if(e.key==='Enter')c.click()}});sentence();stats()}
function openLesson(i){let l=A.tracks[track].lessons[i],tips=['핵심 표현을 소리 내어 3번 읽고 의미를 확인하세요.','문장의 핵심 단어를 먼저 찾고 전체 의미를 연결하세요.','정답보다 왜 맞고 틀리는지 근거를 확인하세요.'];let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><button class="modal-x" aria-label="닫기">×</button><div class="lesson-icon">${l[0]}</div><p class="eyebrow">${A.tracks[track].tag} · MINI LESSON</p><h2>${l[1]}</h2><p class="muted">${l[2]}</p><div class="tip"><b>오늘의 학습법</b><p>${tips[i%3]}</p></div><button class="primary complete">학습 완료 · +10 XP</button></div>`;document.body.appendChild(m);m.querySelector('.modal-x').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('.complete').onclick=()=>{xp+=10;done++;save();stats();$('#xp').textContent=xp;m.querySelector('.complete').textContent='완료했습니다 ✓';m.querySelector('.complete').disabled=true;setTimeout(()=>m.remove(),700)}}
function sentence(){let d=A.tracks[track],s=d.sentences[idx%d.sentences.length];$('#practiceTag').textContent=d.tag+' · SHADOWING';$('#sentence').textContent=s[0];$('#translation').textContent=s[1];$('#feedback').textContent='먼저 음성을 듣고 문장을 따라 말해보세요.'}
$$('.nav').forEach(n=>n.onclick=()=>{$$('.nav,.view').forEach(x=>x.classList.remove('active'));n.classList.add('active');$('#'+n.dataset.view).classList.add('active');if(n.dataset.view==='practice')prepareVoices()});
function prepareVoices(){const load=()=>{voices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith(A.lang.slice(0,2).toLowerCase()));voiceInfo()};load();speechSynthesis.onvoiceschanged=load;setTimeout(load,500)}
function pick(kind){const male=['david','daniel','mark','alex','james','guy','male','yong','yunyang','강호','민준'],female=['samantha','zira','susan','aria','jenny','female','yuna','huihui','xiaoxiao','선희','유나'],h=kind==='female'?female:male,f=voices.find(v=>h.some(x=>v.name.toLowerCase().includes(x)));return f||voices[kind==='female'?voices.length-1:0]||null}
function voiceInfo(){let row=$('.speaker');if(!row)return;let info=$('#voiceStatus');if(!info){info=document.createElement('p');info.id='voiceStatus';info.className='voice-status';row.after(info)}let m=pick('male'),f=pick('female');info.textContent=voices.length?`남성: ${m?.name||'기본'} · 여성: ${f?.name||'기본'}`:'기기 음성을 불러오는 중입니다…'}
$$('.voice').forEach(v=>v.onclick=()=>{gender=v.dataset.gender==='1'?'female':'male';$$('.voice').forEach(x=>x.classList.remove('active'));v.classList.add('active');speak()});function speak(){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance($('#sentence').textContent);u.lang=A.lang;u.rate=.86;u.pitch=gender==='female'?1.08:.92;u.voice=pick(gender);u.onerror=()=>$('#feedback').textContent='이 기기의 음성을 사용할 수 없습니다. Chrome 또는 Safari에서 다시 시도해 주세요.';speechSynthesis.speak(u);$('#feedback').textContent=`${gender==='female'?'여성':'남성'} 음성을 재생하고 있습니다.`}$('#listen').onclick=speak;$('#next').onclick=()=>{idx++;sentence()};
$('#record').onclick=()=>{let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#feedback').textContent='이 브라우저는 음성 인식을 지원하지 않습니다. Chrome에서 열어 주세요.';return}let r=new SR();r.lang=A.lang;r.interimResults=false;r.maxAlternatives=1;$('#feedback').textContent='마이크를 듣고 있어요… 지금 말해 주세요.';r.onresult=e=>{let heard=e.results[0][0].transcript,s=similarity($('#sentence').textContent,heard);best=s+'%';xp+=Math.round(s/10);done++;save();$('#feedback').innerHTML=`<b>${s}% 일치</b><br>인식: ${heard}<br>${s>=80?'아주 좋아요!':s>=60?'좋아요. 한 번 더 연습해 보세요.':'음성을 다시 듣고 천천히 따라 해보세요.'}`;stats()};r.onerror=e=>$('#feedback').textContent=e.error==='not-allowed'?'주소창의 자물쇠에서 마이크를 허용해 주세요.':'음성을 인식하지 못했습니다. 다시 시도해 주세요.';r.start()};
function similarity(a,b){let n=s=>s.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,'').split(/\s+/).filter(Boolean),x=n(a),y=n(b);return Math.min(100,Math.round(x.filter(w=>y.includes(w)).length/Math.max(x.length,1)*100))}function save(){localStorage[P+'xp']=xp;localStorage[P+'done']=done;localStorage[P+'best']=best}function stats(){$('#xpStat').textContent=xp;$('#doneStat').textContent=done;$('#bestStat').textContent=best}
