const DATA=[
 {id:"CO-DEMO-001",city:"daegu",ko:"팔공 키친 데모",en:"Palgong Kitchen Demo",cuisine:{ko:"한식",en:"Korean"},price:2,tags:["family","casual","local"],distance:2.3,rating:4.7,reviews:386,hours:{ko:"데모 · 11:30–22:00",en:"Demo · 11:30–22:00"},phone:"DEMO — not callable",address:{ko:"대구광역시 데모구 101 (가상)",en:"101 Demo-gu, Daegu (fictional)"},momentum:8,complaints:"stable"},
 {id:"CO-DEMO-002",city:"daegu",ko:"서문 국수 실험실",en:"Seomun Noodle Lab",cuisine:{ko:"면요리",en:"Noodles"},price:1,tags:["solo","casual","local"],distance:1.1,rating:4.5,reviews:241,hours:{ko:"데모 · 10:30–20:30",en:"Demo · 10:30–20:30"},phone:"DEMO — not callable",address:{ko:"대구광역시 데모구 202 (가상)",en:"202 Demo-gu, Daegu (fictional)"},momentum:13,complaints:"down"},
 {id:"CO-DEMO-003",city:"daegu",ko:"수성 리모네 테스트",en:"Suseong Limone Test",cuisine:{ko:"이탈리안",en:"Italian"},price:3,tags:["date","quiet"],distance:4.8,rating:4.8,reviews:192,hours:{ko:"데모 · 17:30–23:00",en:"Demo · 17:30–23:00"},phone:"DEMO — not callable",address:{ko:"대구광역시 데모구 303 (가상)",en:"303 Demo-gu, Daegu (fictional)"},momentum:5,complaints:"stable"},
 {id:"CO-DEMO-004",city:"seoul",ko:"연남 반상 데모",en:"Yeonnam Table Demo",cuisine:{ko:"한식",en:"Korean"},price:2,tags:["family","local","quiet"],distance:.9,rating:4.6,reviews:612,hours:{ko:"데모 · 11:00–21:30",en:"Demo · 11:00–21:30"},phone:"DEMO — not callable",address:{ko:"서울특별시 데모구 404 (가상)",en:"404 Demo-gu, Seoul (fictional)"},momentum:11,complaints:"down"},
 {id:"CO-DEMO-005",city:"seoul",ko:"을지 화로 테스트",en:"Eulji Grill Test",cuisine:{ko:"고기",en:"Korean BBQ"},price:2,tags:["business","lively","local"],distance:1.7,rating:4.4,reviews:903,hours:{ko:"데모 · 16:00–01:00",en:"Demo · 16:00–01:00"},phone:"DEMO — not callable",address:{ko:"서울특별시 데모구 505 (가상)",en:"505 Demo-gu, Seoul (fictional)"},momentum:-3,complaints:"up"},
 {id:"CO-DEMO-006",city:"seoul",ko:"한남 소라 샘플",en:"Hannam Sora Sample",cuisine:{ko:"이탈리안",en:"Italian"},price:3,tags:["date","quiet"],distance:3.5,rating:4.9,reviews:328,hours:{ko:"데모 · 18:00–23:00",en:"Demo · 18:00–23:00"},phone:"DEMO — not callable",address:{ko:"서울특별시 데모구 606 (가상)",en:"606 Demo-gu, Seoul (fictional)"},momentum:7,complaints:"stable"},
 {id:"CO-DEMO-007",city:"newyork",ko:"머서 파스타 데모",en:"Mercer Pasta Demo",cuisine:{ko:"이탈리안",en:"Italian"},price:2,tags:["date","casual","local"],distance:1.1,rating:4.7,reviews:744,hours:{ko:"데모 · 12:00–22:30",en:"Demo · 12 PM–10:30 PM"},phone:"DEMO — not callable",address:{ko:"뉴욕 Demo Street 707 (가상)",en:"707 Demo Street, New York (fictional)"},momentum:9,complaints:"down"},
 {id:"CO-DEMO-008",city:"newyork",ko:"오차드 테이블 테스트",en:"Orchard Table Test",cuisine:{ko:"아메리칸",en:"American"},price:2,tags:["family","casual"],distance:2.3,rating:4.5,reviews:521,hours:{ko:"데모 · 09:00–23:00",en:"Demo · 9 AM–11 PM"},phone:"DEMO — not callable",address:{ko:"뉴욕 Demo Street 808 (가상)",en:"808 Demo Street, New York (fictional)"},momentum:4,complaints:"stable"},
 {id:"CO-DEMO-009",city:"newyork",ko:"블리커 누들 샘플",en:"Bleecker Noodle Sample",cuisine:{ko:"아시안",en:"Asian"},price:1,tags:["solo","lively","local"],distance:.7,rating:4.6,reviews:1102,hours:{ko:"데모 · 11:30–24:00",en:"Demo · 11:30 AM–12 AM"},phone:"DEMO — not callable",address:{ko:"뉴욕 Demo Street 909 (가상)",en:"909 Demo Street, New York (fictional)"},momentum:15,complaints:"down"}
];
const TEXT={ko:{area:"지역",want:"먹고 싶은 음식·상황",price:"가격",party:"동행",mood:"분위기",find:"가장 잘 맞는 3곳 찾기",demoTitle:"현재 테스트 데이터",demoBody:"아래 식당은 기능 검증용 가상 데이터입니다. 실제 식당·전화·영업정보로 사용하지 마세요.",top3:"TOP 3 RECOMMENDATIONS",best:"지금 가장 잘 맞는 3곳",location:"내 위치 사용",savedTitle:"저장한 식당",tasteTitle:"나의 취향",saveTaste:"취향 저장",deleteData:"내 테스트 데이터 삭제",deviceOnly:"GitHub 테스트판의 저장값은 이 기기에만 유지됩니다.",discover:"찾기",saved:"저장",taste:"취향"},en:{area:"Area",want:"Food or occasion",price:"Price",party:"Party",mood:"Atmosphere",find:"Find my best three",demoTitle:"Current test data",demoBody:"These are fictional records for feature testing. Do not use them as real restaurant, phone or opening information.",top3:"TOP 3 RECOMMENDATIONS",best:"Your best three right now",location:"Use my location",savedTitle:"Saved restaurants",tasteTitle:"My taste",saveTaste:"Save taste",deleteData:"Delete my test data",deviceOnly:"GitHub test data is saved only on this device.",discover:"Discover",saved:"Saved",taste:"Taste"}};
let locale=localStorage.getItem("cookora-out-locale")||"ko",saved=JSON.parse(localStorage.getItem("worldtaste-saved")||"[]"),history=JSON.parse(localStorage.getItem("worldtaste-search-history")||"[]"),taste=JSON.parse(localStorage.getItem("worldtaste-taste")||'{"spicy":50,"local":75,"waiting":40,"child":true}'),current=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function text(){return TEXT[locale]}
function score(r){let n=60+(r.rating-4)*12+Math.max(-5,Math.min(12,r.momentum));const price=+$("#price").value,party=$("#party").value,mood=$("#mood").value,q=$("#query").value.toLowerCase();if(r.price<=price)n+=7;if(r.tags.includes(party))n+=10;if(r.tags.includes(mood))n+=8;if(r.tags.includes("local"))n+=taste.local/20;if(q&&[r.ko,r.en,r.cuisine.ko,r.cuisine.en,...r.tags].some(x=>String(x).toLowerCase().includes(q)))n+=12;return Math.min(99,Math.round(n))}
function reason(r){const out=[];if(r.tags.includes($("#party").value))out.push(locale==="ko"?"동행 조건에 적합":"Fits your party");if(r.tags.includes($("#mood").value))out.push(locale==="ko"?"원하는 분위기":"Matches the mood");if(r.tags.includes("local")&&taste.local>60)out.push(locale==="ko"?"로컬 선호 반영":"Matches local preference");if(r.momentum>7)out.push(locale==="ko"?"최근 평판 상승":"Recent reputation rising");return out.slice(0,2).join(" · ")||(locale==="ko"?"평점·거리·취향의 균형":"Balanced rating, distance and taste")}
function card(r,i){const momentum=(r.momentum>=0?"+":"")+r.momentum+"%",complaints=r.complaints==="up"?(locale==="ko"?"최근 불만 증가":"Complaints rising"):(locale==="ko"?"최근 불만 안정":"Complaints stable");return `<article class="card"><div class="photo ${i%3===1?'orange':i%3===2?'gold':''}"><b class="demo">DEMO DATA</b><strong>#${i+1} · ${r.cuisine[locale]}</strong></div><div class="card-body"><small>${r.id}</small><h3>${r[locale]}</h3><div class="meta"><span>★ ${r.rating.toFixed(1)} (${r.reviews})</span><span>${'$'.repeat(r.price)}</span><span>${r.distance} km</span></div><p class="reason">✦ ${reason(r)}</p><div class="momentum"><span><b>${momentum}</b> Rating Momentum</span><span>${complaints}</span></div><p><b>${score(r)}%</b> AI match</p><div class="actions"><button onclick="openDetail('${r.id}')">${locale==='ko'?'상세':'Details'}</button><button class="${saved.includes(r.id)?'saved':''}" onclick="toggleSave('${r.id}')">${saved.includes(r.id)?'♥ '+(locale==='ko'?'저장됨':'Saved'):'♡ '+(locale==='ko'?'저장':'Save')}</button></div></div></article>`}
function search(){const city=$("#city").value;current=DATA.filter(r=>r.city===city).sort((a,b)=>score(b)-score(a)).slice(0,3);history.unshift({city,query:$("#query").value,at:new Date().toISOString()});history=history.slice(0,20);localStorage.setItem("worldtaste-search-history",JSON.stringify(history));render()}
function render(){if(!current.length)current=DATA.filter(r=>r.city===$("#city").value).sort((a,b)=>score(b)-score(a)).slice(0,3);$("#cards").innerHTML=current.map(card).join("");const kept=DATA.filter(r=>saved.includes(r.id));$("#savedCards").innerHTML=kept.length?kept.map(card).join(""):`<div class="profile">${locale==='ko'?'아직 저장한 데모 식당이 없습니다.':'No demo restaurants saved yet.'}</div>`}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("worldtaste-saved",JSON.stringify(saved));toast(saved.includes(id)?(locale==='ko'?"저장했습니다":"Saved"):(locale==='ko'?"저장을 취소했습니다":"Removed"));render()}
function openDetail(id){const r=DATA.find(x=>x.id===id);$("#detail").innerHTML=`<div class="overlay" onclick="if(event.target===this)closeDetail()"><article class="detail"><button class="close" onclick="closeDetail()">✕</button><span class="demo">DEMO DATA</span><h2>${r[locale]}</h2><p class="reason">✦ ${reason(r)}</p><dl><div><dt>${locale==='ko'?'주소':'Address'}</dt><dd>${r.address[locale]}</dd></div><div><dt>${locale==='ko'?'전화':'Phone'}</dt><dd>${r.phone}</dd></div><div><dt>${locale==='ko'?'영업시간':'Hours'}</dt><dd>${r.hours[locale]}</dd></div><div><dt>Rating Momentum / Recent Reputation</dt><dd>${r.momentum>=0?'+':''}${r.momentum}% · ${r.complaints}</dd></div><div><dt>${locale==='ko'?'데이터 상태':'Data status'}</dt><dd>DEMO DATA · ${locale==='ko'?'실제 식당 정보 아님':'not live restaurant information'} · refreshed 2026-09-27</dd></div></dl><div class="actions"><button onclick="toggleSave('${r.id}')">♡ ${locale==='ko'?'저장':'Save'}</button><button onclick="window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('${r[locale]}'),'_blank')">${locale==='ko'?'외부 지도 검색':'Search map'}</button></div></article></div>`}
function closeDetail(){$("#detail").innerHTML=""}
function showView(id){$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!==id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='saved')render()}
function applyLanguage(){document.documentElement.lang=locale;$("#langButton").textContent=locale==='ko'?'EN':'한국어';$("#headline").textContent=locale==='ko'?'오늘 어디서 먹을까요?':'Where should I eat?';$("#tagline").textContent=locale==='ko'?'조건을 알려주면 가장 잘 맞는 3곳만 골라드려요.':'Tell us what matters and we will narrow it to three.';$("#query").placeholder=locale==='ko'?'예: 아이와 조용히 먹을 한식':'e.g. quiet Korean food with children';$$('[data-t]').forEach(x=>x.textContent=text()[x.dataset.t]);current=[];render()}
function toggleLanguage(){locale=locale==='ko'?'en':'ko';localStorage.setItem('cookora-out-locale',locale);applyLanguage()}
function saveTaste(){taste={spicy:+$("#spicy").value,local:+$("#local").value,waiting:+$("#waiting").value,child:$("#child").checked};localStorage.setItem('worldtaste-taste',JSON.stringify(taste));current=[];render();toast(locale==='ko'?'취향을 저장했습니다':'Taste saved')}
function deleteAccount(){if(confirm(locale==='ko'?'이 기기의 Cookora Out 테스트 데이터를 삭제할까요?':'Delete Cookora Out test data on this device?')){['worldtaste-saved','worldtaste-search-history','worldtaste-taste'].forEach(k=>localStorage.removeItem(k));saved=[];history=[];taste={spicy:50,local:75,waiting:40,child:true};initTaste();render()}}
function initTaste(){$("#spicy").value=taste.spicy;$("#local").value=taste.local;$("#waiting").value=taste.waiting;$("#child").checked=!!taste.child}
function useLocation(){if(!navigator.geolocation)return toast(locale==='ko'?'위치 기능을 지원하지 않습니다':'Location unavailable');navigator.geolocation.getCurrentPosition(()=>toast(locale==='ko'?'위치 권한이 확인되었습니다. 테스트 데이터에는 거리를 재계산하지 않습니다.':'Location permission confirmed. Demo distances are unchanged.'),()=>toast(locale==='ko'?'위치 권한을 확인해주세요':'Check location permission'),{timeout:7000})}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$("#searchForm").addEventListener('submit',e=>{e.preventDefault();search()});$("#city").addEventListener('change',()=>{current=[];render()});initTaste();applyLanguage();
