/* ScoreStep V2 hotfix 216: real AI gateway + exam target integration. */
(()=>{
 const app=C.id,langCode=app==='topik'?'ko':app==='hsk'?'zh':'en',examName=app==='topik'?'TOPIK':app==='hsk'?'HSK':'IELTS'; let lastConversationText='';
 const gatewayUrl=()=>String((window.LANGUAGE_APP_RUNTIME||{}).aiEndpoint||C.aiEndpoint||'').replace(/\/$/,'');
 window.requestAIConversation=async function(userText){const endpoint=gatewayUrl();if(!endpoint)throw new Error('AI_GATEWAY_NOT_CONFIGURED');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:langCode,exam:examName,level:localStorage[K+'level']||null,scenario:convSession?.mode||'free',message:userText,conversationHistory:(convSession?.history||[]).slice(-12).map(x=>({role:x.role,content:x.text})),track:C.id==='ielts'?(localStorage[K+'level']||''):undefined,showTranslation:localStorage[K+'hsk-translation']!=='off'}),signal:controller.signal});if(!res.ok)throw new Error('AI_GATEWAY_'+res.status);const data=await res.json();if(!data||typeof data.reply!=='string'||!data.reply.trim())throw new Error('AI_GATEWAY_INVALID_RESPONSE');return data}finally{clearTimeout(timer)}};
 function storeTurn(userMessage,aiMessage){const key=K+'conversation-records';let rows=[];try{rows=JSON.parse(localStorage[key]||'[]')}catch(e){}rows.push({language:langCode,exam:examName,level:localStorage[K+'level']||null,scenario:convSession?.mode||'free',userMessage,aiMessage,timestamp:new Date().toISOString()});localStorage[key]=JSON.stringify(rows.slice(-100))}
 const errorCopy=()=>app==='topik'?'AI 튜터에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.':app==='hsk'?'暂时无法连接 AI 老师，请稍后再试。':'AI tutor is temporarily unavailable. Please try again.';
 window.submitConversation=async function(text){text=String(text||'').trim();if(!text||!convSession)return;lastConversationText=text;if(aiTurnsRemaining()<=0){q('#conversationStatus').textContent='오늘의 무료 AI 대화 5회를 모두 사용했습니다.';return}convSession.history.push({role:'user',text});convSession.turns++;renderConversation();const send=q('#conversationSend');if(send)send.disabled=true;q('#conversationStatus').textContent=app==='hsk'?'AI 老师正在回复…':app==='ielts'?'AI tutor is responding…':'AI 튜터가 답변을 준비하고 있습니다…';try{const result=await requestAIConversation(text);consumeAITurn();convSession.history.push({role:'assistant',text:result.reply});convSave(convSession.history);storeTurn(text,result.reply);renderConversation();try{speakText(result.speechText||result.reply)}catch(e){}q('#conversationStatus').textContent=app==='hsk'?'AI 实时对话':app==='ielts'?'Live AI conversation':'AI 실시간 대화';state.xp+=5;state.done++;save();render();conversationFeedback(text,result);if(result.feedback&&q('#conversationFeedback')){q('#conversationFeedback').innerHTML='<b>'+(app==='ielts'?'Estimated practice feedback':app==='hsk'?'学习反馈':'학습 피드백')+'</b><p>'+convEsc(result.feedback)+'</p>';q('#conversationFeedback').classList.remove('hide')}}catch(err){console.error('[AI conversation]',err);q('#conversationStatus').innerHTML=convEsc(errorCopy())+' <button id="conversationRetry" class="btn soft" type="button">Retry</button>';q('#conversationRetry').onclick=()=>submitConversation(lastConversationText)}finally{if(send)send.disabled=false}};
 document.addEventListener('click',e=>{if(e.target.closest?.('.nav[data-page="conversation"]'))setTimeout(()=>initConversationUI(),0)});setTimeout(()=>{const input=q('#conversationInput');if(input)input.setAttribute('enterkeyhint','send')},0);
 const targetKey=()=>K+'target-exam',targetExam=()=>{try{return JSON.parse(localStorage[targetKey()]||'null')}catch(e){return null}};
 function seoulDayDiff(date){const now=new Date(),seoulNow=new Date(now.toLocaleString('en-US',{timeZone:'Asia/Seoul'})),today=Date.UTC(seoulNow.getFullYear(),seoulNow.getMonth(),seoulNow.getDate()),[y,m,d]=date.split('-').map(Number);return Math.ceil((Date.UTC(y,m-1,d)-today)/86400000)}
 window.scheduleDays=seoulDayDiff;const previousDailyPlanInfo=dailyPlanInfo;window.dailyPlanInfo=function(){const base=previousDailyPlanInfo(),target=targetExam();if(target?.date)base.days=Math.max(0,seoulDayDiff(target.date));return base};
 window.renderExamSchedule=function(schedule,verifiedAt){const home=q('#home');if(!home)return;q('#examSchedule')?.remove();const upcoming=(schedule.events||[]).filter(x=>seoulDayDiff(x.date)>=0).slice(0,6),selected=targetExam(),box=document.createElement('section');box.id='examSchedule';box.className='card';box.style.marginTop='16px';const selectedHtml=selected?`<div class="card" style="margin:10px 0"><p class="eyebrow">MY EXAM</p><h3>${convEsc(selected.name||selected.exam)}</h3><b style="font-size:24px">D-${Math.max(0,seoulDayDiff(selected.date))}</b><p>${convEsc(selected.date)}</p><button id="clearTargetExam" class="btn soft">Change Exam</button></div>`:'';const rows=upcoming.map(x=>`<div class="review-item"><span><b>${convEsc(x.name)}</b><br>시험 ${convEsc(x.date)} · D-${Math.max(0,seoulDayDiff(x.date))}<br><small>접수 ${convEsc(x.registration||'공식 사이트 확인')} · 발표 ${convEsc(x.result||'공식 사이트 확인')}</small></span><button class="btn soft use-exam-date" data-date="${convEsc(x.date)}" data-name="${convEsc(x.name)}">My Exam</button></div>`).join('');const dynamic=schedule.dynamic?'<p><b>IELTS:</b> 지역·Academic/General·시험센터에 따라 예약 가능 날짜가 달라집니다. 공식 예약 시스템에서 실시간 날짜를 선택하세요.</p>':'';box.innerHTML=`<p class="eyebrow">EXAM SCHEDULE</p><h3>${convEsc(schedule.label)}</h3>${selectedHtml}${rows||dynamic}<p class="small">${convEsc(schedule.note||'')}<br>Source: ${convEsc(schedule.sourceLabel||'Official source')} · Last updated: ${convEsc(verifiedAt||'')}</p><a class="btn soft" target="_blank" rel="noopener noreferrer" href="${convEsc(schedule.source)}">공식 일정 확인</a>`;home.appendChild(box);qa('.use-exam-date').forEach(b=>b.onclick=()=>{const value={exam:examName,name:b.dataset.name,date:b.dataset.date};localStorage[targetKey()]=JSON.stringify(value);let p=JSON.parse(localStorage[K+'profile']||'{}');p.date=value.date;p.goal=value.name;localStorage[K+'profile']=JSON.stringify(p);render();renderExamSchedule(schedule,verifiedAt)});q('#clearTargetExam')?.addEventListener('click',()=>{localStorage.removeItem(targetKey());render();renderExamSchedule(schedule,verifiedAt)})};
 setTimeout(loadExamSchedule,100);
})();