let pantry=JSON.parse(localStorage.getItem("wc-pantry")||'[{"n":"rice","q":2,"u":"cup"},{"n":"egg","q":4,"u":"piece"},{"n":"tomato","q":3,"u":"piece"},{"n":"onion","q":2,"u":"piece"},{"n":"garlic","q":1,"u":"head"},{"n":"soy sauce","q":1,"u":"bottle"}]'),fav=JSON.parse(localStorage.getItem("wc-fav")||"[]"),done=JSON.parse(localStorage.getItem("wc-done")||"[]"),filter="all",query="",current=null,step=0,timer=null,seconds=0,chefState=null,photoFile=null,detected=[],visionModel=null,mobileModel=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function save(){localStorage.setItem("wc-pantry",JSON.stringify(pantry));localStorage.setItem("wc-fav",JSON.stringify(fav));localStorage.setItem("wc-done",JSON.stringify(done))}
function lang(){return $("#lang").value}function tx(){return I[lang()]||I.en}function recipeName(r){let n=window.RECIPE_NAME_I18N&&window.RECIPE_NAME_I18N[r.id]&&window.RECIPE_NAME_I18N[r.id][lang()];if(n)return n;let v=window.RECIPE_I18N[r.id];return lang()==="en"||!v||!v[lang()]?r.n:v[lang()][0]}function recipeSteps(r){let v=window.RECIPE_I18N[r.id];return lang()==="en"||!v||!v[lang()]?r.s:v[lang()][1]}function countryName(r){return lang()==="en"?r.c:((window.COUNTRY_I18N[lang()]||{})[r.c]||r.c)}function ingredientName(n){return lang()==="en"?n:((window.INGREDIENT_I18N[lang()]||{})[n]||n)}
function missing(r){let h=new Set(pantry.map(i=>i.n));return r.x.filter(x=>!h.has(x))}function visible(r){let miss=missing(r).length;if(filter==="zero"&&!r.z)return false;if(["0","1","2"].includes(filter)&&miss!==+filter)return false;return (recipeName(r)+countryName(r)+r.n+r.c).toLowerCase().includes(query.toLowerCase())}
function card(r){let miss=missing(r),t=tx();return '<article class="card"><div class="art" style="background:radial-gradient(circle at 65% 30%,#fff8,transparent 36%),'+r.co+'"><span>'+r.f+'</span><span class="status">'+(miss.length?t.missing+" "+miss.length:t.ready)+'</span><button class="heart" onclick="toggleFav(\''+r.id+'\',event)">'+(fav.includes(r.id)?"♥":"♡")+'</button></div><div class="body" onclick="openRecipe(\''+r.id+'\')"><div class="meta">'+countryName(r)+' · '+t.world+'</div><h3>'+recipeName(r)+'</h3><div class="small">◷ '+r.m+' '+t.min+' · 🔥 '+wcCalories(r,1)+' '+wcNutritionText(lang()).unit+' · '+t.easy+' '+(r.z?"· ♻ "+t.zero:"")+'</div></div></article>'}
function render(){let list=R.filter(visible),t=tx();$("#cards").innerHTML=list.map(card).join("");$("#savedCards").innerHTML=R.filter(r=>fav.includes(r.id)).map(card).join("")||'<div class="panel">'+t.none+'</div>';$("#pantryRows").innerHTML=pantry.map((i,n)=>{let expiry="",tone="";if(i.e){let days=Math.ceil((new Date(i.e+"T23:59:59")-new Date())/86400000);expiry=" · "+t.best+" "+i.e+(days<0?" · ⚠ "+({en:"expired",ko:"기한 지남",es:"caducado",ja:"期限切れ",zh:"已过期"}[lang()]):days<=2?" · ⚠ "+({en:"use soon",ko:"우선 사용",es:"usar pronto",ja:"早めに使用",zh:"尽快使用"}[lang()]):"");tone=days<0?" style=\"color:var(--red);font-weight:800\"":""}return '<div class="row"><span style="font-size:24px">🥬</span><div class="grow"><b>'+ingredientName(i.n)+'</b><div class="small"'+tone+'>'+i.q+' '+i.u+expiry+'</div></div><button class="trash" onclick="removePantry('+n+')">'+t.remove+'</button></div>'}).join("");$("#pantryCount").textContent="("+pantry.length+" "+t.items+")";$("#heroChips").innerHTML=pantry.slice(0,6).map(i=>'<span class="chip">'+ingredientName(i.n)+'</span>').join("");$("#readyCount").textContent=R.filter(r=>missing(r).length===0).length;$("#passportGrid").innerHTML=R.map(r=>'<div class="chip" style="text-align:center;opacity:'+(done.includes(r.id)?1:.4)+';font-size:28px">'+r.f+'<small style="display:block;font-size:11px">'+countryName(r)+'</small></div>').join("")}
function setView(v){["explore","pantry","saved","passport"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==v));$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===v));render()}function addPantry(){let n=$("#ingredient").value.trim().toLowerCase();if(!n)return;pantry=pantry.filter(x=>x.n!==n);pantry.unshift({n,q:+$("#qty").value||1,u:$("#unit").value,e:$("#expiry").value});$("#ingredient").value="";save();render()}function removePantry(n){pantry.splice(n,1);save();render()}function toggleFav(id,e){e.stopPropagation();fav=fav.includes(id)?fav.filter(x=>x!==id):fav.concat(id);save();render()}
function loadScript(src){return new Promise((ok,no)=>{let old=document.querySelector('script[src="'+src+'"]');if(old)return old.dataset.ready?ok():old.addEventListener("load",ok,{once:true});let s=document.createElement("script");s.src=src;s.onload=()=>{s.dataset.ready=1;ok()};s.onerror=no;document.head.appendChild(s)})}
function previewPhoto(e){photoFile=e.target.files&&e.target.files[0];if(!photoFile)return;let img=$("#photoPreview");img.src=URL.createObjectURL(photoFile);img.classList.remove("hidden");$("#photoEmpty").classList.add("hidden");$("#scanButton").disabled=false;$("#scanStatus").textContent=PUI[lang()].ready;detected=[];renderCandidates()}
const FOOD={banana:"banana",apple:"apple",orange:"orange",broccoli:"broccoli",carrot:"carrot",sandwich:"bread",pizza:"cheese","hot dog":"sausage",cake:"cake",donut:"bread",bowl:"mixed ingredients",bottle:"bottled ingredient"};
