window.EXTRA_RECIPES=[
{id:"pho",n:"Quick Chicken Pho",c:"Vietnam",f:"🇻🇳",m:35,z:1,x:["rice noodles","chicken","onion","ginger","lime","herbs"],s:["Toast the onion and ginger until fragrant.","Simmer them with chicken and water to make a light broth.","Cook the rice noodles separately and divide into bowls.","Add chicken and broth, then finish with lime and herbs."],co:"#4b996f"},
{id:"shakshuka",n:"Skillet Shakshuka",c:"Tunisia",f:"🇹🇳",m:30,z:1,x:["egg","tomato","onion","bell pepper","garlic","cumin"],s:["Soften onion and bell pepper in a skillet.","Add garlic, cumin, and tomato and simmer until thick.","Make wells in the sauce and crack in the eggs.","Cover and cook until the whites set."],co:"#c75036"},
{id:"hummus",n:"Creamy Hummus Plate",c:"Lebanon",f:"🇱🇧",m:15,z:1,x:["chickpeas","tahini","lemon","garlic","olive oil","bread"],s:["Rinse the chickpeas and reserve a little liquid.","Blend chickpeas, tahini, lemon, and garlic.","Add liquid gradually until very smooth.","Top with olive oil and serve with bread."],co:"#d2a85c"},
{id:"curry",n:"Coconut Vegetable Curry",c:"Sri Lanka",f:"🇱🇰",m:35,z:1,x:["potato","carrot","onion","coconut milk","curry powder","rice"],s:["Cook onion and curry powder until fragrant.","Add potato and carrot and stir well.","Pour in coconut milk and simmer until tender.","Season and serve with rice."],co:"#db8b27"},
{id:"feijoada",n:"Weeknight Black Bean Stew",c:"Brazil",f:"🇧🇷",m:40,z:1,x:["black beans","sausage","onion","garlic","orange","rice"],s:["Brown the sliced sausage in a deep pan.","Add onion and garlic and cook until soft.","Stir in black beans and simmer until rich.","Serve with rice and fresh orange."],co:"#357b4a"},
{id:"lomo",n:"Peruvian Lomo Saltado",c:"Peru",f:"🇵🇪",m:25,x:["beef","onion","tomato","potato","soy sauce","rice"],s:["Cook the potato until crisp and keep warm.","Sear the beef quickly over high heat.","Add onion, tomato, and soy sauce and toss briefly.","Serve immediately with potato and rice."],co:"#b54b36"},
{id:"nasi",n:"Indonesian Nasi Goreng",c:"Indonesia",f:"🇮🇩",m:20,z:1,x:["rice","egg","chicken","onion","garlic","soy sauce"],s:["Use cold rice and break up any clumps.","Cook onion, garlic, and chicken in a hot pan.","Add rice and soy sauce and stir-fry well.","Top with a fried egg."],co:"#ad4a35"},
{id:"adobo",n:"Filipino Chicken Adobo",c:"Philippines",f:"🇵🇭",m:45,x:["chicken","soy sauce","vinegar","garlic","bay leaf","rice"],s:["Combine chicken, soy sauce, vinegar, garlic, and bay leaf.","Bring to a simmer without stirring at first.","Cook until the chicken is tender and the sauce reduces.","Serve over hot rice."],co:"#7f5635"},
{id:"moussaka",n:"Easy Greek Moussaka",c:"Greece",f:"🇬🇷",m:55,x:["eggplant","ground beef","tomato","onion","milk","cheese"],s:["Brown the eggplant slices until tender.","Cook beef, onion, and tomato into a thick sauce.","Layer eggplant and meat sauce in a baking dish.","Top with milk sauce and cheese, then bake until golden."],co:"#547eb2"},
{id:"jollof",n:"One-Pot Jollof Rice",c:"Nigeria",f:"🇳🇬",m:45,z:1,x:["rice","tomato","bell pepper","onion","garlic","chicken"],s:["Blend tomato, bell pepper, onion, and garlic.","Cook the sauce until reduced and fragrant.","Add rice, chicken, and enough water to cook.","Cover and steam gently until the rice is tender."],co:"#d75b28"}
];

window.RECIPE_I18N={
bibimbap:{ko:["알록달록 비빔밥",["쌀을 씻어 고슬고슬하게 밥을 짓습니다.","당근, 버섯, 시금치를 각각 볶습니다.","달걀을 반숙으로 부칩니다.","밥 위에 재료를 담고 간장으로 간합니다."]],es:["Bibimbap arcoíris",["Cuece el arroz hasta que quede suelto.","Saltea por separado la zanahoria, los champiñones y las espinacas.","Fríe el huevo dejando la yema tierna.","Coloca todo sobre el arroz y sazona con salsa de soja."]],ja:["彩りビビンバ",["ご飯をふっくら炊きます。","にんじん、きのこ、ほうれん草を別々に炒めます。","卵を半熟の目玉焼きにします。","ご飯に具を盛り、しょうゆで味を調えます。"]],zh:["彩虹拌饭",["把米饭煮至松软。","分别炒熟胡萝卜、蘑菇和菠菜。","煎一个溏心荷包蛋。","把食材摆在米饭上，用酱油调味。"]]},
tacos:{ko:["팬트리 콩 타코",["다진 양파와 콩을 함께 데웁니다.","마른 팬에 토르티야를 굽습니다.","콩, 토마토, 치즈를 채웁니다.","라임즙을 뿌려 냅니다."]],es:["Tacos de frijoles de despensa",["Calienta los frijoles con cebolla picada.","Tuesta las tortillas en una sartén seca.","Rellena con frijoles, tomate y queso.","Termina con lima y sirve."]],ja:["常備豆のタコス",["刻んだ玉ねぎと豆を温めます。","乾いたフライパンでトルティーヤを焼きます。","豆、トマト、チーズを包みます。","ライムを絞って仕上げます。"]],zh:["储藏豆塔可",["把豆子和切碎的洋葱一起加热。","在干锅中烘热玉米饼。","加入豆子、番茄和奶酪。","挤上青柠汁即可。"]]},
pasta:{ko:["부드러운 토마토 파스타",["소금을 넉넉히 넣은 물에 파스타를 삶습니다.","올리브유에 마늘을 약불로 익힙니다.","토마토를 넣고 윤기가 날 때까지 끓입니다.","면수와 치즈를 넣어 파스타와 버무립니다."]],es:["Pasta sedosa con tomate",["Cuece la pasta en agua bien salada.","Cocina suavemente el ajo en aceite de oliva.","Añade el tomate y deja reducir.","Mezcla con agua de cocción y queso."]],ja:["なめらかトマトパスタ",["塩をきかせた湯でパスタをゆでます。","オリーブ油でにんにくを弱火で炒めます。","トマトを加えてつやが出るまで煮ます。","ゆで汁とチーズを加えて和えます。"]],zh:["丝滑番茄意面",["在充分加盐的水中煮意面。","用橄榄油小火煸香大蒜。","加入番茄，煮至浓亮。","加入面汤和奶酪拌匀。"]]},
oyakodon:{ko:["포근한 오야코동",["얇게 썬 양파를 간장, 설탕, 물에 끓입니다.","닭고기를 넣어 완전히 익힙니다.","푼 달걀을 둘러 붓고 잠시 뚜껑을 덮습니다.","뜨거운 밥 위에 올립니다."]],es:["Oyakodon reconfortante",["Cuece la cebolla con soja, azúcar y agua.","Añade el pollo y cocínalo por completo.","Vierte el huevo batido y tapa brevemente.","Sirve sobre arroz caliente."]],ja:["やさしい親子丼",["薄切り玉ねぎをしょうゆ、砂糖、水で煮ます。","鶏肉を加えて火を通します。","溶き卵を回し入れ、短時間ふたをします。","熱いご飯にのせます。"]],zh:["暖心亲子丼",["用酱油、糖和水煮洋葱片。","加入鸡肉煮熟。","淋入蛋液并短暂盖锅。","盛在热米饭上。"]]},
dal:{ko:["황금 렌틸 달",["렌틸콩을 씻어 부드러워질 때까지 끓입니다.","양파, 마늘, 커리 가루, 토마토를 볶습니다.","향신료 베이스를 렌틸콩에 섞습니다.","간을 맞춰 밥과 냅니다."]],es:["Dal dorado de lentejas",["Enjuaga las lentejas y cuécelas hasta que estén tiernas.","Cocina cebolla, ajo, curry y tomate.","Incorpora la base especiada a las lentejas.","Sazona y sirve con arroz."]],ja:["黄金レンズ豆ダール",["レンズ豆を洗い、柔らかく煮ます。","玉ねぎ、にんにく、カレー粉、トマトを炒めます。","香味ベースを豆に混ぜます。","味を調え、ご飯と盛ります。"]],zh:["黄金扁豆达尔",["洗净扁豆并煮至软烂。","炒香洋葱、大蒜、咖喱粉和番茄。","把香料底料拌入扁豆。","调味后配米饭食用。"]]},
friedrice:{ko:["태국 바질 볶음밥",["식감을 위해 찬밥을 준비합니다.","센 불에 마늘과 달걀을 볶습니다.","밥과 간장을 넣고 고루 볶습니다.","바질을 섞고 라임즙으로 마무리합니다."]],es:["Arroz frito tailandés con albahaca",["Usa arroz frío para una mejor textura.","Fríe el ajo y el huevo a fuego alto.","Añade arroz y salsa de soja y saltea.","Incorpora albahaca y termina con lima."]],ja:["タイバジル炒飯",["冷やご飯をほぐしておきます。","強火でにんにくと卵を炒めます。","ご飯としょうゆを加えて炒め合わせます。","バジルを混ぜ、ライムで仕上げます。"]],zh:["泰式罗勒炒饭",["使用冷米饭以获得更好的口感。","大火炒香大蒜和鸡蛋。","加入米饭和酱油翻炒均匀。","拌入罗勒，挤青柠汁收尾。"]]},
tortilla:{ko:["스페인 감자 토르티야",["감자와 양파를 얇게 썹니다.","올리브유에 약불로 부드럽게 익힙니다.","푼 달걀과 섞어 5분간 둡니다.","팬에서 익힌 뒤 뒤집어 속까지 익힙니다."]],es:["Tortilla española de patatas",["Corta finas la patata y la cebolla.","Cocínalas lentamente en aceite de oliva.","Mézclalas con huevo batido y reposa cinco minutos.","Cuaja en sartén, gira y termina el centro."]],ja:["スペイン風ポテトオムレツ",["じゃがいもと玉ねぎを薄切りにします。","オリーブ油で柔らかくなるまで弱火で煮ます。","溶き卵と混ぜて5分休ませます。","フライパンで焼き、返して中心まで火を通します。"]],zh:["西班牙土豆蛋饼",["把土豆和洋葱切成薄片。","用橄榄油小火煮至柔软。","与蛋液混合，静置五分钟。","平底锅煎制，翻面至中心凝固。"]]},
ratatouille:{ko:["평일 라타투이",["모든 채소를 비슷한 크기로 깍둑썹니다.","올리브유에 양파와 마늘을 익힙니다.","가지, 주키니, 토마토 순으로 넣습니다.","뚜껑을 덮어 부드럽게 끓입니다."]],es:["Ratatouille entre semana",["Corta todas las verduras en dados parejos.","Ablanda cebolla y ajo en aceite de oliva.","Añade berenjena, calabacín y luego tomate.","Tapa y cocina hasta que quede meloso."]],ja:["平日のラタトゥイユ",["野菜を同じ大きさに角切りします。","オリーブ油で玉ねぎとにんにくを炒めます。","なす、ズッキーニ、トマトの順に加えます。","ふたをして柔らかく煮ます。"]],zh:["家常普罗旺斯炖菜",["把所有蔬菜切成大小均匀的丁。","用橄榄油炒软洋葱和大蒜。","依次加入茄子、西葫芦和番茄。","盖锅慢炖至柔软。"]]},
pho:{ko:["간편 닭고기 쌀국수",["양파와 생강을 향이 나도록 굽습니다.","닭고기와 물을 넣어 맑은 육수를 끓입니다.","쌀국수를 따로 삶아 그릇에 나눕니다.","닭고기와 육수를 붓고 라임과 허브를 올립니다."]],es:["Pho rápido de pollo",["Tuesta cebolla y jengibre hasta que desprendan aroma.","Cuécelos con pollo y agua para hacer un caldo ligero.","Cuece los fideos de arroz por separado.","Añade pollo y caldo; termina con lima y hierbas."]],ja:["簡単チキンフォー",["玉ねぎとしょうがを香ばしく焼きます。","鶏肉と水を加えて澄んだスープを作ります。","米麺を別にゆでて器に分けます。","鶏肉とスープを注ぎ、ライムと香草を添えます。"]],zh:["快手鸡肉河粉",["烤香洋葱和姜。","加入鸡肉和水，熬成清汤。","另锅煮熟河粉并分装。","加入鸡肉和汤，以青柠和香草收尾。"]]},
shakshuka:{ko:["팬 샥슈카",["팬에서 양파와 피망을 부드럽게 익힙니다.","마늘, 큐민, 토마토를 넣어 걸쭉하게 끓입니다.","소스에 홈을 내고 달걀을 깨 넣습니다.","뚜껑을 덮어 흰자가 익을 때까지 조리합니다."]],es:["Shakshuka en sartén",["Ablanda cebolla y pimiento en una sartén.","Añade ajo, comino y tomate; reduce.","Haz huecos en la salsa y casca los huevos.","Tapa y cocina hasta que cuajen las claras."]],ja:["フライパン・シャクシュカ",["玉ねぎとパプリカを柔らかく炒めます。","にんにく、クミン、トマトを加えて煮詰めます。","ソースにくぼみを作り、卵を割り入れます。","ふたをして白身が固まるまで加熱します。"]],zh:["平底锅北非蛋",["在锅中炒软洋葱和彩椒。","加入大蒜、孜然和番茄，煮至浓稠。","在酱汁中挖窝并打入鸡蛋。","盖锅煮至蛋白凝固。"]]},
hummus:{ko:["크리미 후무스 플레이트",["병아리콩을 헹구고 물을 조금 남깁니다.","병아리콩, 타히니, 레몬, 마늘을 갈아줍니다.","남긴 물을 조금씩 넣어 매끈하게 만듭니다.","올리브유를 두르고 빵과 냅니다."]],es:["Plato de hummus cremoso",["Enjuaga los garbanzos y reserva algo de líquido.","Tritura garbanzos, tahini, limón y ajo.","Añade líquido poco a poco hasta que quede fino.","Corona con aceite de oliva y sirve con pan."]],ja:["クリーミーフムスプレート",["ひよこ豆を洗い、汁を少し残します。","ひよこ豆、タヒニ、レモン、にんにくを攪拌します。","汁を少しずつ加え、なめらかにします。","オリーブ油をかけ、パンと盛ります。"]],zh:["绵滑鹰嘴豆泥拼盘",["冲洗鹰嘴豆并留少量液体。","搅打鹰嘴豆、芝麻酱、柠檬和大蒜。","逐渐加液体至细腻顺滑。","淋橄榄油并配面包。"]]},
curry:{ko:["코코넛 채소 커리",["양파와 커리 가루를 향이 나도록 볶습니다.","감자와 당근을 넣어 섞습니다.","코코넛밀크를 붓고 부드러워질 때까지 끓입니다.","간을 맞춰 밥과 냅니다."]],es:["Curry de verduras con coco",["Cocina cebolla y curry hasta que desprendan aroma.","Añade patata y zanahoria y mezcla.","Vierte leche de coco y cuece hasta que estén tiernas.","Sazona y sirve con arroz."]],ja:["ココナッツ野菜カレー",["玉ねぎとカレー粉を香りよく炒めます。","じゃがいもとにんじんを加えて混ぜます。","ココナッツミルクを注ぎ、柔らかく煮ます。","味を調え、ご飯と盛ります。"]],zh:["椰香蔬菜咖喱",["炒香洋葱和咖喱粉。","加入土豆和胡萝卜翻匀。","倒入椰奶，炖至蔬菜变软。","调味后配米饭食用。"]]},
feijoada:{ko:["간편 검은콩 스튜",["깊은 팬에서 소시지를 노릇하게 굽습니다.","양파와 마늘을 넣어 부드럽게 익힙니다.","검은콩을 넣고 진해질 때까지 끓입니다.","밥과 생오렌지를 곁들입니다."]],es:["Guiso rápido de frijoles negros",["Dora la salchicha en una olla.","Añade cebolla y ajo y cocina hasta ablandar.","Incorpora los frijoles negros y deja espesar.","Sirve con arroz y naranja fresca."]],ja:["手軽な黒豆シチュー",["深い鍋でソーセージを焼きます。","玉ねぎとにんにくを加えて柔らかくします。","黒豆を加えて濃くなるまで煮ます。","ご飯と生のオレンジを添えます。"]],zh:["快手黑豆炖锅",["在深锅中煎香香肠。","加入洋葱和大蒜炒软。","拌入黑豆，炖至浓郁。","配米饭和新鲜橙子食用。"]]},
lomo:{ko:["페루 로모 살타도",["감자를 바삭하게 익혀 따뜻하게 둡니다.","센 불에 쇠고기를 빠르게 굽습니다.","양파, 토마토, 간장을 넣어 짧게 볶습니다.","감자와 밥을 곁들여 바로 냅니다."]],es:["Lomo saltado peruano",["Cocina la patata hasta que quede crujiente.","Sella la carne rápidamente a fuego alto.","Añade cebolla, tomate y soja y saltea brevemente.","Sirve enseguida con patata y arroz."]],ja:["ペルー風ロモ・サルタード",["じゃがいもをカリッと焼いて保温します。","牛肉を強火で素早く焼きます。","玉ねぎ、トマト、しょうゆを加えてさっと炒めます。","じゃがいもとご飯を添えてすぐ盛ります。"]],zh:["秘鲁炒牛柳",["把土豆煎至酥脆并保温。","大火快速煎香牛肉。","加入洋葱、番茄和酱油快速翻炒。","立即配土豆和米饭食用。"]]},
nasi:{ko:["인도네시아 나시고렝",["찬밥의 덩어리를 풀어줍니다.","센 팬에 양파, 마늘, 닭고기를 볶습니다.","밥과 간장을 넣어 고루 볶습니다.","달걀 프라이를 올립니다."]],es:["Nasi goreng indonesio",["Usa arroz frío y separa los grumos.","Cocina cebolla, ajo y pollo en sartén caliente.","Añade arroz y soja y saltea bien.","Corona con un huevo frito."]],ja:["インドネシア風ナシゴレン",["冷やご飯のかたまりをほぐします。","熱いフライパンで玉ねぎ、にんにく、鶏肉を炒めます。","ご飯としょうゆを加えてよく炒めます。","目玉焼きをのせます。"]],zh:["印尼炒饭",["使用冷米饭并打散结块。","热锅炒香洋葱、大蒜和鸡肉。","加入米饭和酱油充分翻炒。","放上一个煎蛋。"]]},
adobo:{ko:["필리핀 치킨 아도보",["닭고기, 간장, 식초, 마늘, 월계수잎을 합칩니다.","처음에는 젓지 말고 끓입니다.","닭이 부드럽고 소스가 졸아들 때까지 익힙니다.","뜨거운 밥 위에 냅니다."]],es:["Adobo filipino de pollo",["Combina pollo, soja, vinagre, ajo y laurel.","Lleva a hervor suave sin remover al principio.","Cuece hasta que el pollo esté tierno y reduzca la salsa.","Sirve sobre arroz caliente."]],ja:["フィリピン風チキンアドボ",["鶏肉、しょうゆ、酢、にんにく、ローリエを合わせます。","最初は混ぜずに煮立てます。","鶏肉が柔らかくなり、汁が煮詰まるまで加熱します。","熱いご飯にかけます。"]],zh:["菲律宾酱醋鸡",["混合鸡肉、酱油、醋、大蒜和月桂叶。","先不搅拌，煮至微沸。","炖至鸡肉软嫩、酱汁收浓。","浇在热米饭上。"]]},
moussaka:{ko:["간편 그리스 무사카",["가지 조각을 부드럽게 굽습니다.","다진 쇠고기, 양파, 토마토를 걸쭉하게 볶습니다.","베이킹 접시에 가지와 고기 소스를 층층이 담습니다.","우유 소스와 치즈를 올려 노릇하게 굽습니다."]],es:["Musaca griega fácil",["Dora las rodajas de berenjena hasta ablandar.","Cocina carne, cebolla y tomate hasta espesar.","Alterna berenjena y salsa de carne en una fuente.","Cubre con salsa de leche y queso y hornea."]],ja:["簡単ギリシャ風ムサカ",["なすを柔らかく焼きます。","牛ひき肉、玉ねぎ、トマトを濃く煮ます。","耐熱皿になすとミートソースを重ねます。","ミルクソースとチーズをのせ、黄金色に焼きます。"]],zh:["简易希腊慕萨卡",["煎软茄子片。","把牛肉、洋葱和番茄煮成浓酱。","在烤盘中交替铺茄子和肉酱。","盖上奶香酱和奶酪，烤至金黄。"]]},
jollof:{ko:["원팟 졸로프 라이스",["토마토, 피망, 양파, 마늘을 갈아줍니다.","소스가 졸고 향이 날 때까지 볶습니다.","쌀, 닭고기, 적당한 물을 넣습니다.","뚜껑을 덮어 쌀이 익을 때까지 약불로 뜸 들입니다."]],es:["Arroz jollof en una olla",["Tritura tomate, pimiento, cebolla y ajo.","Cocina la salsa hasta que reduzca.","Añade arroz, pollo y agua suficiente.","Tapa y cocina suavemente hasta que el arroz esté tierno."]],ja:["ワンポット・ジョロフライス",["トマト、パプリカ、玉ねぎ、にんにくを攪拌します。","ソースを香りよく煮詰めます。","米、鶏肉、適量の水を加えます。","ふたをして米が柔らかくなるまで弱火で炊きます。"]],zh:["一锅西非番茄饭",["搅打番茄、彩椒、洋葱和大蒜。","把酱汁煮至浓缩出香。","加入米、鸡肉和足量的水。","盖锅小火焖至米饭熟软。"]]}
};

window.COUNTRY_I18N={ko:{Korea:"한국",Mexico:"멕시코",Italy:"이탈리아",Japan:"일본",India:"인도",Thailand:"태국",Spain:"스페인",France:"프랑스",Vietnam:"베트남",Tunisia:"튀니지",Lebanon:"레바논","Sri Lanka":"스리랑카",Brazil:"브라질",Peru:"페루",Indonesia:"인도네시아",Philippines:"필리핀",Greece:"그리스",Nigeria:"나이지리아"},es:{Korea:"Corea",Mexico:"México",Italy:"Italia",Japan:"Japón",India:"India",Thailand:"Tailandia",Spain:"España",France:"Francia",Vietnam:"Vietnam",Tunisia:"Túnez",Lebanon:"Líbano","Sri Lanka":"Sri Lanka",Brazil:"Brasil",Peru:"Perú",Indonesia:"Indonesia",Philippines:"Filipinas",Greece:"Grecia",Nigeria:"Nigeria"},ja:{Korea:"韓国",Mexico:"メキシコ",Italy:"イタリア",Japan:"日本",India:"インド",Thailand:"タイ",Spain:"スペイン",France:"フランス",Vietnam:"ベトナム",Tunisia:"チュニジア",Lebanon:"レバノン","Sri Lanka":"スリランカ",Brazil:"ブラジル",Peru:"ペルー",Indonesia:"インドネシア",Philippines:"フィリピン",Greece:"ギリシャ",Nigeria:"ナイジェリア"},zh:{Korea:"韩国",Mexico:"墨西哥",Italy:"意大利",Japan:"日本",India:"印度",Thailand:"泰国",Spain:"西班牙",France:"法国",Vietnam:"越南",Tunisia:"突尼斯",Lebanon:"黎巴嫩","Sri Lanka":"斯里兰卡",Brazil:"巴西",Peru:"秘鲁",Indonesia:"印度尼西亚",Philippines:"菲律宾",Greece:"希腊",Nigeria:"尼日利亚"}};

window.INGREDIENT_I18N={ko:{rice:"쌀",egg:"달걀",spinach:"시금치",carrot:"당근",mushroom:"버섯","soy sauce":"간장",tortilla:"토르티야",beans:"콩",tomato:"토마토",onion:"양파",lime:"라임",cheese:"치즈",pasta:"파스타",garlic:"마늘","olive oil":"올리브유",chicken:"닭고기",sugar:"설탕",lentils:"렌틸콩","curry powder":"커리 가루",basil:"바질",potato:"감자",salt:"소금",zucchini:"주키니",eggplant:"가지","rice noodles":"쌀국수",ginger:"생강",herbs:"허브","bell pepper":"피망",cumin:"큐민",chickpeas:"병아리콩",tahini:"타히니",lemon:"레몬",bread:"빵","coconut milk":"코코넛밀크","black beans":"검은콩",sausage:"소시지",orange:"오렌지",beef:"쇠고기",vinegar:"식초","bay leaf":"월계수잎","ground beef":"다진 쇠고기",milk:"우유"},es:{rice:"arroz",egg:"huevo",spinach:"espinacas",carrot:"zanahoria",mushroom:"champiñones","soy sauce":"salsa de soja",tortilla:"tortilla",beans:"frijoles",tomato:"tomate",onion:"cebolla",lime:"lima",cheese:"queso",pasta:"pasta",garlic:"ajo","olive oil":"aceite de oliva",chicken:"pollo",sugar:"azúcar",lentils:"lentejas","curry powder":"curry",basil:"albahaca",potato:"patata",salt:"sal",zucchini:"calabacín",eggplant:"berenjena","rice noodles":"fideos de arroz",ginger:"jengibre",herbs:"hierbas","bell pepper":"pimiento",cumin:"comino",chickpeas:"garbanzos",tahini:"tahini",lemon:"limón",bread:"pan","coconut milk":"leche de coco","black beans":"frijoles negros",sausage:"salchicha",orange:"naranja",beef:"carne de res",vinegar:"vinagre","bay leaf":"laurel","ground beef":"carne picada",milk:"leche"},ja:{rice:"米",egg:"卵",spinach:"ほうれん草",carrot:"にんじん",mushroom:"きのこ","soy sauce":"しょうゆ",tortilla:"トルティーヤ",beans:"豆",tomato:"トマト",onion:"玉ねぎ",lime:"ライム",cheese:"チーズ",pasta:"パスタ",garlic:"にんにく","olive oil":"オリーブ油",chicken:"鶏肉",sugar:"砂糖",lentils:"レンズ豆","curry powder":"カレー粉",basil:"バジル",potato:"じゃがいも",salt:"塩",zucchini:"ズッキーニ",eggplant:"なす","rice noodles":"米麺",ginger:"しょうが",herbs:"香草","bell pepper":"パプリカ",cumin:"クミン",chickpeas:"ひよこ豆",tahini:"タヒニ",lemon:"レモン",bread:"パン","coconut milk":"ココナッツミルク","black beans":"黒豆",sausage:"ソーセージ",orange:"オレンジ",beef:"牛肉",vinegar:"酢","bay leaf":"ローリエ","ground beef":"牛ひき肉",milk:"牛乳"},zh:{rice:"大米",egg:"鸡蛋",spinach:"菠菜",carrot:"胡萝卜",mushroom:"蘑菇","soy sauce":"酱油",tortilla:"玉米饼",beans:"豆子",tomato:"番茄",onion:"洋葱",lime:"青柠",cheese:"奶酪",pasta:"意面",garlic:"大蒜","olive oil":"橄榄油",chicken:"鸡肉",sugar:"糖",lentils:"扁豆","curry powder":"咖喱粉",basil:"罗勒",potato:"土豆",salt:"盐",zucchini:"西葫芦",eggplant:"茄子","rice noodles":"河粉",ginger:"姜",herbs:"香草","bell pepper":"彩椒",cumin:"孜然",chickpeas:"鹰嘴豆",tahini:"芝麻酱",lemon:"柠檬",bread:"面包","coconut milk":"椰奶","black beans":"黑豆",sausage:"香肠",orange:"橙子",beef:"牛肉",vinegar:"醋","bay leaf":"月桂叶","ground beef":"牛肉末",milk:"牛奶"}};
